theme = "smol"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "asimplemuse"

# Parameters
[params]
    subtitle = "Your blog subtitle goes here!"
    dateFmt = ""

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/elioamicarelli"
        weight = 1 

    [[menu.footer]]
        name = "Linkedin"
        url = "linkedin.com/in/elioamicarelli"
        weight = 2 

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/ElioAmicarelli"
        weight = 3 